### PR TITLE
add checkbox

### PR DESCRIPTION
**Pull request by suguanYang**
I just added an option that supports checkboxes.
can you give me some suggestion?
if ok, I will complete the test code
image

### CODE REVIEW

**Comment by enmand** [comment]
Hi @suguanYang! Before accepting this code into our repository, we ask that you sign our Contributors Licensed Agreement (the link is here: https://github.com/manifoldco/promptui/pull/99#issuecomment-475939454)

We also need at least 30% test coverage on the patch in order for our tooling to allow a merge.

Thanks!

**Comment by suguanYang** [comment]
> Hi @suguanYang! Before accepting this code into our repository, we ask that you sign our Contributors License Agreement (the link is here: [#99 (comment)](https://github.com/manifoldco/promptui/pull/99#issuecomment-475939454))
> 
> We also need at least 30% test coverage on the patch in order for our tooling to allow a merge.
> 
> Thanks!

I'm sorry, I just realized this feature may have many conflicts with old ones, like the `search` option, as the current code what I added can't support to get the correct index. I am afraid that I don't have enough energy to adjustment code in a short time.

**Comment by rubiin** [comment]
@suguanYang how to achieve multiple select

**Comment by suguanYang** [comment]
> @suguanYang how to achieve multiple select

https://github.com/suguanYang/promptui/tree/checkbox

and you can use 
```
promptui.Select{
		Label:       "LabelName",
		Checkbox:    true,
		ChosedIcon:  promptui.IconGood,
		ChosenIndex: &chosedIndex,
		Items:       items,
	}
```

**Comment by rubiin** [comment]
thanks

**Pull request closed without merging**
