### PR TITLE
Fixed echo of cursor after input is finished. (fixes #117)

### LINKED ISSUE #117: Prompt resource doesn't remove cursor when ENTER key is pressed.
image
Code:
```
prompt = promptui.Prompt{
	Label: "Prompt 3",
}
_, err = prompt.Run()
```

The string that I get back from prompt.Run doesn't include the cursor, though.

### PR DESCRIPTION
**Pull request by jamesdobson**
Based on: https://github.com/manifoldco/promptui/pull/118 by github.com/richardmcsong,
taking only the changes required to fix issue #117.

### CODE REVIEW

**Comment by bithavoc** [comment]
Can we merge this?

**Comment by bithavoc** [comment]
can we merge this?

**Comment by bithavoc** [comment]
can we merge this?

**Comment by VDMSean** [comment]
@bithavoc don't make me turn this car around

**Comment by bithavoc** [comment]
@vdmsean Sorry I'm not following, what do you mean?

**Review by MoonBarc — APPROVED** [review]
I don't really review things but I want this to be merged. lgtm

**Comment by jamesdobson** [comment]
Maybe @jbowes or @jeffandersen can merge?

**Review by jbowes — APPROVED** [review]
Thank you!

**Pull request merged**
